<?php
session_start();
require_once 'classes/base/abstractbase.class.php';
require_once "classes/config.class.php";
config::include_database();
require_once "classes/object.class.php";
require_once "classes/core.class.php";
$coreC = new core;
require_once "classes/search.class.php";
$searchC = new search;
require_once "classes/users.class.php";
$usersC = new users;
require_once "classes/auth.class.php";
$authC = new auth;
$uinfo = users::get_user_info($_SESSION['user_id']);
require_once "classes/mark.class.php";
$markC = new mark;
require_once "classes/filters.class.php";
$filtersC = new filters;
require_once "classes/sections.class.php";
$sectionsC = new sections;
require_once "classes/threads.class.php";
$threadsC = new threads;
require_once "classes/messages.class.php";
$messagesC = new messages;
require_once "classes/faq.class.php";
$faqC = new faq;
require 'classes/rss.class.php';
$rssC = new rss;
?>