# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 15 Jun 2009 02:44:03 -0700
*               @ALL          1
*               @user         8
