<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Mon, 15 Jun 2009 02:44:03 -0700
 */
$conf['title'] = 'RULINUX Wiki: Техническая документация';
$conf['lang'] = 'ru';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
